In [45]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#CHATGPT helped me modify this code to work. I had problems with the shape later on in the code

data = pd.read_excel("exchange_rate_data.xlsx")

data['Date'] = pd.to_datetime(data['Date'])

dateData = data['Date']

data['PrevExchangeRate'] = data['ExchangeRate'].shift(1)
data['PrevExchangeRate2'] = data['ExchangeRate'].shift(2)
data['PrevExchangeRate3'] = data['ExchangeRate'].shift(3)

data['Date'] = data['Date'].apply(lambda x: x.toordinal()).astype(float)

X = data[['PrevExchangeRate', 'PrevExchangeRate2', 'PrevExchangeRate3', 'Date']][3:]
y = data['ExchangeRate'][3:]

print(X)
print(y)

     PrevExchangeRate  PrevExchangeRate2  PrevExchangeRate3      Date
3             20700.0            20600.0            21600.0  738218.0
4             20750.0            20700.0            20600.0  738219.0
5             20750.0            20750.0            20700.0  738220.0
6             20775.0            20750.0            20750.0  738221.0
7             21700.0            20775.0            20750.0  738222.0
..                ...                ...                ...       ...
761           89600.0            89600.0            89600.0  738976.0
762           89600.0            89600.0            89600.0  738977.0
763           89600.0            89600.0            89600.0  738978.0
764           89600.0            89600.0            89600.0  738979.0
765           89600.0            89600.0            89600.0  738980.0

[763 rows x 4 columns]
3      20750
4      20750
5      20775
6      21700
7      21700
       ...  
761    89600
762    89600
763    89600
764    89600
765   

In [46]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.1, shuffle = False)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, shuffle = False)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

y_train = y_train.values.reshape(-1, 1)
y_val = y_val.values.reshape(-1, 1)
y_test = y_test.values.reshape(-1, 1)

scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train)
y_val_scaled = scaler_y.transform(y_val)
y_test_scaled = scaler_y.transform(y_test)


X_train_reshaped = np.reshape(X_train_scaled, (X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_val_reshaped = np.reshape(X_val_scaled, (X_val_scaled.shape[0], 1, X_val_scaled.shape[1]))
X_test_reshaped = np.reshape(X_test_scaled, (X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

print(X_train_reshaped)
print(y_train_scaled)

[[[-1.42265874 -1.42140448 -1.38309007 -1.72952779]]

 [[-1.42096379 -1.41801752 -1.41693304 -1.72447807]]

 [[-1.42096379 -1.41632404 -1.41354874 -1.71942836]]

 ...

 [[ 0.91298153  0.91559599  0.91823134  1.71942836]]

 [[ 0.91298153  0.91559599  0.91823134  1.72447807]]

 [[ 0.91298153  0.91559599  0.91823134  1.72952779]]]
[[-1.42561426]
 [-1.42561426]
 [-1.42476605]
 [-1.39338206]
 [-1.39338206]
 [-1.32213192]
 [-1.32382836]
 [-1.37302488]
 [-1.35860521]
 [-1.36454272]
 [-1.36963201]
 [-1.38320347]
 [-1.3687838 ]
 [-1.37302488]
 [-1.33315873]
 [-1.34588197]
 [-1.3526677 ]
 [-1.34079267]
 [-1.32467657]
 [-1.33400695]
 [-1.31195333]
 [-1.30856047]
 [-1.3102569 ]
 [-1.30856047]
 [-1.30516761]
 [-1.30007831]
 [-1.3153462 ]
 [-1.32552479]
 [-1.32552479]
 [-1.32552479]
 [-1.32722122]
 [-1.32552479]
 [-1.32552479]
 [-1.32552479]
 [-1.3153462 ]
 [-1.32891765]
 [-1.32213192]
 [-1.32213192]
 [-1.31195333]
 [-1.31195333]
 [-1.29159615]
 [-1.29498902]
 [-1.29498902]
 [-1.29498902]
 [-1.29498

In [47]:

model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, input_shape=(1, X_train_scaled.shape[1])),
    tf.keras.layers.Dense(30, activation='sigmoid'),
    tf.keras.layers.Dense(1)
])

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='mean_squared_error')

history = model.fit(X_train_reshaped, y_train_scaled, epochs=100, batch_size=15, verbose=1, validation_data=(X_val_reshaped, y_val_scaled))

loss = model.evaluate(X_test_reshaped, y_test_scaled)
print(f'Loss on test set: {loss}')


Epoch 1/100
46/46 [==============================] - 1s 7ms/step - loss: 1.1476 - val_loss: 0.0049
Epoch 2/100
46/46 [==============================] - 0s 3ms/step - loss: 0.8534 - val_loss: 3.0513e-04
Epoch 3/100
46/46 [==============================] - 0s 3ms/step - loss: 0.6186 - val_loss: 8.7734e-04
Epoch 4/100
46/46 [==============================] - 0s 3ms/step - loss: 0.4368 - val_loss: 0.0056
Epoch 5/100
46/46 [==============================] - 0s 3ms/step - loss: 0.2967 - val_loss: 0.0124
Epoch 6/100
46/46 [==============================] - 0s 3ms/step - loss: 0.1957 - val_loss: 0.0193
Epoch 7/100
46/46 [==============================] - 0s 3ms/step - loss: 0.1251 - val_loss: 0.0251
Epoch 8/100
46/46 [==============================] - 0s 3ms/step - loss: 0.0781 - val_loss: 0.0287
Epoch 9/100
46/46 [==============================] - 0s 3ms/step - loss: 0.0481 - val_loss: 0.0293
Epoch 10/100
46/46 [==============================] - 0s 3ms/step - loss: 0.0299 - val_loss: 0.0283
E

In [50]:

def predict_exchange_rate(date, prevRate1, prevRae2, prevRate3):
    date_ordinal = pd.to_datetime(date).toordinal()
    date_scaled = scaler.transform([[prevRate1, prevRae2, prevRate3, date_ordinal]])
    date_reshaped = np.reshape(date_scaled, (1, 1, 4))
    predicted_rate = model.predict(date_reshaped, verbose = 0)
    return scaler_y.inverse_transform(predicted_rate[0])[0][0]

future_date = '4/5/2024'
prevRate1 = y[len(y)-1]
prevRate2 = y[len(y)-2]
prevRate3 = y[len(y)-3]
predicted_rate = predict_exchange_rate(future_date, prevRate1, prevRate2, prevRate3)
print(f'Predicted exchange rate for {future_date}: {predicted_rate}')

future_date = '4/6/2024'
predicted_rate2 = predict_exchange_rate(future_date, prevRate1, prevRate2, prevRate3)
print(f'Predicted exchange rate for {future_date}: {predicted_rate2}')

future_date = '4/7/2024'
predicted_rate3 = predict_exchange_rate(future_date, prevRate1, prevRate2, prevRate3)
print(f'Predicted exchange rate for {future_date}: {predicted_rate3}')

future_date = '4/8/2024'
predicted_rate4 = predict_exchange_rate(future_date, prevRate1, prevRate2, prevRate3)
print(f'Predicted exchange rate for {future_date}: {predicted_rate4}')

future_date = '4/9/2024'
predicted_rate5 = predict_exchange_rate(future_date, prevRate1, prevRate2, prevRate3)
print(f'Predicted exchange rate for {future_date}: {predicted_rate5}')



/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Predicted exchange rate for 4/5/2024: 89820.25
Predicted exchange rate for 4/6/2024: 89818.3828125


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Predicted exchange rate for 4/7/2024: 89816.5
Predicted exchange rate for 4/8/2024: 89814.6171875
Predicted exchange rate for 4/9/2024: 89812.7265625


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [51]:
import joblib

model.save("exchangeRateModel" + ".h5")
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(scaler_y, 'scaler_y.pkl')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


['scaler_y.pkl']